### ISSUE TITLE
example/example.cpp does not compile

### ISSUE THREAD

**Issue by vinifr** [linkingvision/rapidonvif#9]
The example code in rapidonvif/onvif/example/example.cpp does not compile. I tried this command but it fails:

_arm-linux-gnueabihf-g++ example/example.cpp -o example -Wall -Wextra -Wshadow -Wformat-security -Winit-self -Wmissing-prototypes -O2 -DLINUX -Iinclude  -DUSE_WEBSOCKET -I/home/pi/projs/evd/onvif_output/output/raspberry-pi3-32bit/include -I./include -I./include/video -I./src/ -I../3rdparty/live555/BasicUsageEnvironment/include  -I../3rdparty/live555/groupsock/include -I../3rdparty/live555/liveMedia/include -I../3rdparty/live555/UsageEnvironment/include -I../3rdparty/live555/live555/include/ -I../3rdparty/civetweb/include/ -DNDEBUG -Os  out.linux/build/../3rdparty/civetweb/src/CivetServer.o out.linux/build/src/onvifagentlib.o out.linux/build//src/tinyprocess/process_unix.o out.linux/build/src/tinyprocess/process.o out.linux/build/include/video/h264_bit_reader.o out.linux/build/include/video/h264_parser.o out.linux/build/include/video/h5s_h264_sink.o out.linux/build/include/video/h5slib.o out.linux/build/include/onvifclidevice.pb.o out.linux/build/include/onvifclimedia.pb.o out.linux/build/include/onvifcli.pb.o out.linux/build/include/onvifcliptz.pb.o out.linux/build/../3rdparty/civetweb/src/civetweb.o out.linux/build/example/example.o  -lpthread -lm -lrt -ldl -L/home/pi/projs/evd/onvif_output/output/raspberry-pi3-32bit/lib -llive555 -lprotobuf  -lssl -lcrypto -lpthread -ldl -lstdc++ -lm -Wl,-Bdynamic -lcrypt_

**Comment by xsmart** [comment]
the example is discarded, you can try ./output/Ubuntu-16.04-64bit/bin/onvifagentcli

**Comment by vinifr** [comment]
Alright, thanks.

**Comment by vinifr** [comment]
onvifagentcli did not work either. The problem was reported here: [https://github.com/linkingvision/rapidonvif/issues/10](url)
I think there is some issue in a Makefile.
